### ISSUE TITLE
Text box values get cut-off

### ISSUE THREAD

**Issue by shalomshachne** [shalomshachne/dotNetTools#6]
User forwarded me screenshot - when he puts his user name "igor" in the User text box, the bottom  part of "g" is cut off.  Text should not be cut off in any of the text boxes at top of GUI.

![image](https://user-images.githubusercontent.com/2422124/66863716-4e5a7b00-ef9c-11e9-94a7-2abcb7f1935d.png)

**Comment by ygisrael** [comment]
78ad219a

**Comment by ygisrael** [comment]
I couldn't repeat this, but enlarged the height from 30 to 33
